id: IB3D462F1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T12:25:58+00:00'
last_modified: '2022-06-08T05:13:10.876848+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11958
  title: ཀརྨ་ཀཾ་ཚང་གི་རང་ལུགས་ཆོ་གའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5CE1:
      image_group_id: I1KG12045
      title: ''
      total_pages: 774
      order: 1
      base_file: 5CE1.txt
    4D06:
      image_group_id: I1KG12046
      title: ''
      total_pages: 1030
      order: 2
      base_file: 4D06.txt
    '4233':
      image_group_id: I1KG12047
      title: ''
      total_pages: 716
      order: 3
      base_file: 4233.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
