id: IB3D462F1
legacy_id: P005602
ocr_import_info:
  bdrc_scan_id: W1KG11958
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T12:21:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:11:56.605646+00:00'
last_modified: 2022-08-31 11:13:05.163433
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11958
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11958
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀརྨ་ཀཾ་ཚང་གི་རང་ལུགས་ཆོ་གའི་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.9459742285792959
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG12045:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12045
      total_pages: 774
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12045.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.943851359452001
    legacy_id: v001
  I1KG12047:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12047
      total_pages: 716
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG12047.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9440854595431959
    legacy_id: v003
  I1KG12046:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12046
      total_pages: 1030
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG12046.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.948890082239771
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
