id: P005602
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:06:15.153200
source_metadata:
  id: bdr:W1KG11958
  title: ཀརྨ་ཀཾ་ཚང་གི་རང་ལུགས་ཆོ་གའི་སྐོར།
  author: ''
  volumes:
    e082e1e3ac194bdba1f489c31f774916:
      image_group_id: I1KG12045
      title: ''
      volume_number: 1
      total_pages: 774
      base_file: v001.txt
    f863ad2038bf4129b4308cb1be3fa7f9:
      image_group_id: I1KG12046
      title: ''
      volume_number: 2
      total_pages: 1030
      base_file: v002.txt
    b42ad54a5eff4dbda8c1cc95838d307b:
      image_group_id: I1KG12047
      title: ''
      volume_number: 3
      total_pages: 716
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
